# Generated by Django 5.2.4 on 2025-07-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problema', models.CharField(max_length=200)),
                ('informacao', models.TextField()),
                ('cep', models.CharField(default='Desconhecido', max_length=9)),
                ('rua', models.CharField(default='Desconhecido', max_length=255)),
                ('numero', models.CharField(default='Desconhecido', max_length=10)),
                ('bairro', models.CharField(default='Desconhecido', max_length=100)),
                ('cidade', models.CharField(default='Desconhecido', max_length=100)),
                ('estado', models.CharField(default='--', max_length=2)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
