# Generated by Django 5.2.4 on 2025-07-12 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_poste', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lampada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('LED', 'LED'), ('Fluorescente', 'Fluorescente'), ('Incandescente', 'Incandescente'), ('Halógena', 'Halógena'), ('Outros', 'Outros')], max_length=20)),
                ('vida_util_meses', models.PositiveIntegerField()),
                ('data_instalacao', models.DateField()),
                ('status', models.CharField(choices=[('Funcionando', 'Funcionando'), ('Queimada', 'Queimada'), ('Manutenção', 'Manutenção'), ('Desativada', 'Desativada')], max_length=20)),
                ('poste', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cadastro_poste.poste')),
            ],
        ),
    ]
