# Generated by Django 5.2.4 on 2025-07-12 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_poste', '0002_lampada'),
    ]

    operations = [
        migrations.AddField(
            model_name='lampada',
            name='potencia',
            field=models.PositiveIntegerField(default=60, help_text='Potência em Watts'),
        ),
        migrations.AlterField(
            model_name='lampada',
            name='status',
            field=models.CharField(choices=[('Funcionando', 'Funcionando'), ('Queimada', 'Queimada'), ('Substituída', 'Substituída')], max_length=20),
        ),
        migrations.AlterField(
            model_name='lampada',
            name='tipo',
            field=models.CharField(choices=[('LED', 'LED'), ('Vapor de Sódio', 'Vapor de Sódio'), ('Fluorescente', 'Fluorescente'), ('Incandescente', 'Incandescente'), ('Halógena', 'Halógena'), ('Outros', 'Outros')], max_length=30),
        ),
    ]
