# Generated by Django 5.2 on 2025-07-15 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_poste', '0003_lampada_potencia_alter_lampada_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poste',
            name='status',
            field=models.IntegerField(choices=[(0, 'Recém adicionado'), (1, 'Aguardando'), (2, 'Cancelado'), (3, 'Corrigido')], default=0),
        ),
    ]
